version: "3.8"
services:
    docker-start-app:
        build: ./
        container_name: "web"
        ports:
            - "50:80"
        depends_on:
            - mysql
        environment:
            MYSQL_HOST: mysql
    mysql:
        image: mysql:8.0.23
        ports:
            - "4812:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"